name: rentx
description: RentX - Car Rental

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.5
  google_fonts: ^2.2.0
  intl: ^0.17.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  flutter_map: ^0.14.0
  pinput: ^2.2.11
  geolocator: ^8.2.1
  conditional_builder_null_safety: ^0.0.6
  latlong2: ^0.8.1
  flutter_svg: ^1.0.3
  google_sign_in: ^5.2.4
  cached_network_image: ^3.2.0
  table_calendar: ^3.0.6
  another_flushbar: ^1.10.29
  page_transition: ^2.0.4
  percent_indicator: ^4.2.2
  bloc: ^8.0.1
  flutter_bloc: ^8.0.1
  dropdown_search: ^5.0.2
  flutter_facebook_auth: ^4.1.2
  flutter_portal: ^1.1.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lang/
    - assets/config/

  fonts:
    - family: RentXIcons
      fonts:
        - asset: assets/fonts/RentXIcons.ttf